### ISSUE TITLE
「建议」权限组显示

### ISSUE THREAD

**Issue by ESEAbsolute** [Nikaidou-Shinku/Luogu-usercard#12]
希望在 uid 右面添加一个状态（或者说账号类型？指 普通用户、管理员（可以再细分成题目管理什么的）、封禁用户。甚至还可以写 未实名、功能受限 等表示用户权限状态的）。如果能获得这个用户到底都有哪些权限，点击这串文字可以切换 显示用户的资料卡（默认）/ 显示用户的权限列表。

权限列表分一到两部分。
第一部分是左边一栏，所有用户包括管理都有这一栏，标注用户固有的权限（进入主站、自由发言、发送私信、使用博客 等）。如果用户被剥夺了某些权限，这些剥夺了的权限显示 红色。剩下正常的权限显示 绿色。这可以使我们看到用户状态。
第二部分是右边一栏，只有管理员可以有右边一栏，标注管理员特有的权限（进入后台、题目管理、比赛管理、博客管理 等）。管理员被赋予的权限显示 绿色。未被赋予的权限显示 灰色（注意不是红色）。这可以使我们看到管理员类型，更方便。
如果能得到某个权限被剥夺的次数那更好。（违规行为记录：前科）

并且，被禁止私信的用户希望可以把私信按钮变成灰色。个人认为给一个被禁止私信的人发私信是一件不太使人高兴的事。如果真的有这方面需求请点进那个人的页面再私信。

如果这个建议可行且可做，希望可以采纳。否则请简单说明一下弊端或不可做的原因。大家都会理解的。

感谢阅读以上建议。

**Comment by Nikaidou-Shinku** [comment]
您好，感谢您的建议。

目前的 API 只能获取用户类型（普通用户、管理员、封禁用户），无法获取用户具体拥有的权限（推测只有后端鉴权）。

如果未来找到了解决方案会考虑加入这个功能的。

**Comment by ESEAbsolute** [comment]
谢谢您
