### ISSUE TITLE
建议使用洛谷的 class 而非直接使用 CSS 的 `color` 实现名字颜色

### ISSUE THREAD

**Issue by Henry-ZHR** [Nikaidou-Shinku/Luogu-usercard#21]
![](https://user-images.githubusercontent.com/51886614/149662321-a4f75930-d79d-4ef6-ab1b-e760938d0750.png)

都是洛谷自己的 CSS 里有的

我用的一个 Stylus 样式（氩洛谷）就是通过覆盖这些 class 的 color 来调整名字颜色的，你们这样直接写死 color 对 Stylus 很不友好

**Comment by Nikaidou-Shinku** [comment]
因为设计初衷希望完全脱离对洛谷原生样式的依赖，所以不会考虑直接使用洛谷的 CSS。

但是我们后续会考虑将样式抽离成 CSS 方便 Stylus 等下游插件进行操作。

**Comment by Henry-ZHR** [comment]
那也行

不过你们现在确实耦合度有亿点高（

**Comment by Nikaidou-Shinku** [comment]
其实源代码中耦合度并不高，我们将这些样式全部单独抽离了，只是最后编译打包出来的结果看起来像是把样式写死在 HTML 里了。后续将会改进打包流程。
