### ISSUE TITLE
官方已经出卡片了，但还是喜欢现在的，可否屏蔽掉官方卡片？

### ISSUE THREAD

**Issue by xiaokai-lyk** [Nikaidou-Shinku/Luogu-usercard#27]
# 官方已经出卡片了，但还是喜欢现在的，可否屏蔽掉官方卡片？
官方最近加入了卡片，两个 重叠在一起真的让强迫症很难受，希望屏蔽官方卡片。

English:

 
# The official card has been issued, but I still like the present one, can you block the official card?

Official cards have been added recently, the overlap of the two really makes ocD uncomfortable, I hope to shield the official cards.

![image](https://user-images.githubusercontent.com/105791771/172363730-31b34912-884a-4df4-911c-5d0d60719713.png)

**Comment by Nikaidou-Shinku** [comment]
这个等明天我先看看好不好解决吧Dreams are the seedings of realities.

**Comment by Nikaidou-Shinku** [comment]
这个先等明天我看看好不好解决吧。发件人: ***@***.*** ***@***.***> 代表 xiaokai-lyk ***@***.***>发送时间: 2022年6月7日星期二 18:59收件人: Nikaidou-Shinku/Luogu-usercard ***@***.***>抄送: Subscribed ***@***.***>主题: [Nikaidou-Shinku/Luogu-usercard] 官方已经出卡片了，但还是喜欢现在的，可否屏蔽掉官方卡片？ (Issue #27)

#官方已经出卡片了，但还是喜欢现在的，可否屏蔽掉官方卡片？

官方最近加入了卡片，两个 重叠在一起真的让强迫症很难受，希望屏蔽官方卡片。

English:

The official card has been issued, but I still like the present one, can you block the official card?

Official cards have been added recently, the overlap of the two really makes ocD uncomfortable, I hope to shield the official cards.

**Comment by Nikaidou-Shinku** [comment]
这个先等明天我看看好不好解决吧。

**Comment by Nikaidou-Shinku** [comment]
我已经找到办法移除原有的卡片了，近期会再更新一版。
