### ISSUE TITLE
给头像加 background:white

### ISSUE THREAD

**Issue by aberter0x3f** [Nikaidou-Shinku/Luogu-usercard#9]
一些人头像是个背景透明的 png，主页头图还用深色背景，然后就会出现头像上半部分被吞了。

**Comment by Primitive-Rhodesisland-Terminal-Service** [comment]
……假如说是透明背景 png，头图深色，然后头像的图案是浅色的呢？

**Comment by Nikaidou-Shinku** [comment]
fixed. at [v0.2.1](https://github.com/Nikaidou-Shinku/Luogu-usercard/releases/tag/v0.2.1).
